### ISSUE TITLE
Also working with 61056 build

### ISSUE THREAD

**Issue by frostfire48** [hackrobotman/Nitrox-2.0#3]
Hello hackrobotman,

I was able to make it work with another build of the game (61056) which is the one used by the official steam players at the moment. 
This game build is cracked and I just copied nitrox files (lib, nitrox logs and other files in root)and steam files (in root) from the 60026 build, already working. 

Thank you again !
(idk where I can put simply a comment so I post it in issue)

**Comment by hackrobotman** [comment]
I’ll update the readme. I couldn’t find a more current version than 60026 but i didn’t search very hard. Whered you find 61056? Just another torrent somewhere?

**Comment by frostfire48** [comment]
https://pc-torrent.org/602-subnautica.html

**Comment by hackrobotman** [comment]
Deleted your response bc posting torrent links is probably not the best idea, but ty for the info. Issue is closed glad it’s working for you.
